version: "3.8"

services:

  mysql:
    image: mysql:8.0.28
    container_name: mysqldb

    command: --default-authentication-plugin=mysql_native_password
    restart: always

    ports:
      - "3308:3306"

    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: solnyshko
      MYSQL_PASSWORD: p*sw5*82
      MYSQL_ROOT_PASSWORD: 52*w2HK
