version: "3.8"

services:

  mysql:
    image: mysql:8.0.28
    container_name: mysqldb

    command: --default-authentication-plugin=mysql_native_password
    restart: always

    ports:
      - "3308:3306"

    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: solnyshko
      MYSQL_PASSWORD: p*sw5*82
      MYSQL_ROOT_PASSWORD: 52*w2HK

  app:
    image: spring-app:demo
    container_name: spring-app
    restart: always

    build:
      context: .

    depends_on:
      - mysql

    ports:
      - "8080:8080"

    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: demo
